tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "romkatv/powerlevel10k"
brew "bash-completion"
brew "ctags"
brew "fzf"
brew "git"
brew "pcre"
brew "ncurses"
brew "htop"
brew "irssi"
brew "mas"
brew "nnn"
brew "nvm"
brew "python"
brew "ripgrep"
brew "shellcheck"
brew "terminal-notifier"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "vim"
brew "watch"
brew "wget"
brew "z"
brew "zsh"
brew "zsh-syntax-highlighting"
brew "romkatv/powerlevel10k/powerlevel10k"
cask "alfred"
cask "anki"
cask "bettertouchtool"
cask "calibre"
cask "cheatsheet"
cask "coconutbattery"
cask "dash"
cask "docker"
cask "evernote"
cask "firefox"
cask "font-fira-code"
cask "font-hack"
cask "franz"
cask "go2shell"
cask "google-chrome"
cask "imageoptim"
cask "iterm2"
cask "karabiner-elements"
cask "malwarebytes"
cask "pdf-expert"
cask "postman"
cask "qbittorrent"
cask "recordit"
cask "rescuetime"
cask "steam"
cask "the-unarchiver"
cask "time-out"
cask "tripmode"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
cask "windscribe"
mas "Amphetamine", id: 937984704
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pocket", id: 568494494
mas "Reeder", id: 880001334
mas "Xcode", id: 497799835
