tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "romkatv/powerlevel10k"
brew "ctags"
brew "fzf"
brew "git"
brew "pcre"
brew "python@3.9"
brew "ncurses"
brew "htop"
brew "irssi"
brew "mas"
brew "nnn"
brew "nvm"
brew "ripgrep"
brew "shellcheck"
brew "terminal-notifier"
brew "the_silver_searcher"
brew "tldr"
brew "tmux"
brew "tree"
brew "vim"
brew "watch"
brew "wget"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-history-substring-search"
brew "romkatv/powerlevel10k/powerlevel10k"
cask "1password"
cask "alfred"
cask "anki"
cask "balenaetcher"
cask "bettertouchtool"
cask "brave-browser"
cask "calibre"
cask "cleanshot"
cask "dash"
cask "docker"
cask "evernote"
cask "figma"
cask "firefox"
cask "font-fira-code"
cask "font-hack"
cask "google-chrome"
cask "imageoptim"
cask "istat-menus"
cask "iterm2"
cask "karabiner-elements"
cask "libreoffice"
cask "monolingual"
cask "pdf-expert"
cask "postman"
cask "protonvpn"
cask "qbittorrent"
cask "rectangle"
cask "spotify"
cask "the-unarchiver"
cask "time-out"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
cask "zoom"
mas "Amphetamine", id: 937984704
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Parcel", id: 639968404
mas "Pocket", id: 568494494
mas "Xcode", id: 497799835
